using System;

//using System.Windows.Threading;

namespace PropertyCross.Core.Domain.Model
{
  public class JsonFilePropertySearch : IJsonPropertySearch
  {

    public void FindProperties(string location, int pageNumber, Action<string> callback, Action<Exception> error)
    {
      /*var timer = new DispatcherTimer();
      timer.Interval = TimeSpan.FromSeconds(2);
      timer.Tick += (s,e) =>
        {
          callback(location == "alf" ? locationsResult : listingsResult);
          timer.Stop();
        };
      timer.Start();*/

      callback(location == "alf" ? locationsResult : listingsResult);
    }

    public void FindProperties(double latitude, double longitude, int pageNumber, Action<string> callback, Action<Exception> error)
    {
      FindProperties("foo", 1, callback, error);
    }

    private string locationsResult = @"{
   'request' : {
      'country' : 'uk',
      'language' : 'en',
      'listing_type' : 'buy',
      'location' : 'alford',
      'num_res' : 20,
      'offset' : 0,
      'output' : 'json_xs',
      'page' : 1,
      'pretty' : '1',
      'product_type' : 'realestate',
      'property_type' : 'property',
      'sort' : 'nestoria_rank'
   },
   'response' : {
      'application_response_code' : '200',
      'application_response_text' : 'ambiguous location',
      'attribution' : {
         'img_height' : 20,
         'img_url' : 'http://static.nestoria.co.uk/i/realestate/uk/en/pb.png',
         'img_width' : 200,
         'link_to_img' : 'http://www.nestoria.co.uk'
      },
      'created_http' : 'Mon, 18 Jul 2011 19:42:40 GMT',
      'created_unix' : 1311018160,
      'locations' : [
         {
            'center_lat' : '51.131487',
            'center_long' : '-0.481011',
            'long_title' : 'Alford',
            'place_name' : 'alford_gu6',
            'title' : 'Alford'
         },
         {
            'center_lat' : '57.223792',
            'center_long' : '-2.746543',
            'long_title' : 'Alford, Aberdeenshire',
            'place_name' : 'alford_ab',
            'title' : 'Alford'
         },
         {
            'center_lat' : '53.265506',
            'center_long' : '0.184356',
            'long_title' : 'Alford, Lincolnshire',
            'place_name' : 'alford_ln',
            'title' : 'Alford'
         },
         {
            'center_lat' : '51.084592',
            'center_long' : '-2.565313',
            'long_title' : 'Alford, Castle Cary',
            'place_name' : 'alford_castlecary',
            'title' : 'Alford'
         }
      ],
      'sort' : 'nestoria_rank',
      'status_code' : '200',
      'status_text' : 'OK',
      'thanks' : 'For using the Nestoria API.'
   }
}";

    private string listingsResult = @"{
   'request' : {
      'country' : 'uk',
      'language' : 'en',
      'listing_type' : 'buy',
      'location' : 'brighton',
      'num_res' : 20,
      'offset' : 0,
      'output' : 'json_xs',
      'page' : 1,
      'pretty' : '1',
      'product_type' : 'realestate',
      'property_type' : 'property',
      'sort' : 'nestoria_rank'
   },
   'response' : {
      'application_response_code' : '101',
      'application_response_text' : 'best guess of ambiguous location',
      'attribution' : {
         'img_height' : 20,
         'img_url' : 'http://static.nestoria.co.uk/i/realestate/uk/en/pb.png',
         'img_width' : 200,
         'link_to_img' : 'http://www.nestoria.co.uk'
      },
      'created_http' : 'Fri, 15 Jul 2011 16:30:26 GMT',
      'created_unix' : 1310747426,
      'link_to_url' : 'http://www.nestoria.co.uk/brighton/property/buy/results-20',
      'listings' : [
         {
            'auction_date' : null,
            'bathroom_number' : '1',
            'bedroom_number' : '3',
            'car_spaces' : null,
            'commission' : null,
            'construction_year' : null,
            'datasource_name' : 'Telegraph',
            'guid' : 'g1-TNtQ2cxVWduV2YyUDMyAjMwAlMQ9lUxADMyEDO=Y',
            'img_height' : '120',
            'img_url' : 'http://3.l.uk.nestoria.nestimg.com/1va/a/e/1vaaed323f0814cab72362638c74f8b754e808ceb5.2.jpg',
            'img_width' : '160',
            'keywords' : 'Garden, Terrace, Fireplace, Conservatory, Patio, Central Heating',
            'latitude' : '50.84120',
            'lister_name' : 'Sequence',
            'lister_url' : 'http://rd.nestoria.co.uk/rd?l=VYeIXQsaZsbQbTMsj&url=2-ePz73aTBU4LVGFByDI484Ner8aIMqOymkHO7u54s36bamuqdfN_G5rGpMALFNUMLxpoWrUrrDKrao-5HDMOjCy9prABCggbXYlPRV0RwIbO22U6qH4zcZxI1J_O7Ailr11DxpgEQzlO_QU4hsnGdHXw5_RrZqZKPvK_Nh652EnSXliJxAzrIcWByKEhjKBWXGfabCnXeVujYtXmF-IghljH5kprSKEgKdMuBMaARs86MweHSPy0U47j36_46WQQWPOf-pR2MVWoj0PrE6wTbTVzaVbQDilVr_2qz85N38XTQeDjuMQ8zQQ9uQqXIGZWExj4QhMgWkGeeOXRWakfT7pUygLS1m7kKB0UIjXRnkuZH80vhOlW-aY5egoFtlJ53svZj1N8yXBUr7xmq3PfHex9iPUVAvXgyHdRM-g%3D%3D&v=2&itype=2',
            'listing_type' : 'buy',
            'location_accuracy' : '10',
            'longitude' : '-0.12798',
            'price' : 229950,
            'price_coldrent' : 0,
            'price_currency' : 'GBP',
            'price_formatted' : '229,950 GBP',
            'price_high' : 229950,
            'price_low' : 229950,
            'price_type' : 'fixed',
            'property_type' : 'house',
            'summary' : 'Three bedroom terrace family house which has a landscaped rear garden...',
            'thumb_height' : '60',
            'thumb_url' : 'http://2.l.uk.nestoria.nestimg.com/1va/a/e/1vaaed323f0814cab72362638c74f8b754e808ceb5.1.jpg',
            'thumb_width' : '60',
            'title' : 'Davey Drive, Brighton, BN1 - Garden',
            'updated_in_days' : 10.5,
            'updated_in_days_formatted' : 'last week'
         },
         {
            'auction_date' : null,
            'bathroom_number' : '',
            'bedroom_number' : '2',
            'car_spaces' : null,
            'commission' : null,
            'construction_year' : null,
            'datasource_name' : 'FindaProperty.com',
            'guid' : 'g1-jNtMTOyMTM2kgN==',
            'img_height' : '120',
            'img_url' : 'http://3.l.uk.nestoria.nestimg.com/1vb/a/0/1vba0057588a250854fab088470a19e45d556f4474.2.jpg',
            'img_width' : '160',
            'keywords' : 'Maisonette',
            'latitude' : '50.83870',
            'lister_name' : 'Graves Jenkins',
            'lister_url' : 'http://rd.nestoria.co.uk/rd?l=WVePeXzhgziXiaTzr&url=2-ePz73aTBU4LVGFByDI494Ner8aIMqOymkHO7u54s36bamuqdfN_H5rCuKADFLkMNxpsWrUrrDKrao-5HDMOjCi9ooQBCggbXZVrUV0RwIbO22U6qH4zcZxI1J_O7Ailr1lP9rwQQzlO_QU4hsnGdHXw5_RrZqpWPvKzNgKd0EnSXliJzBjzBfWByKEhjKBWXGfabCnXeVujJqXvb9JQhii7wmsXVKRQbctPKNb0d7MONwKCYJioE_OCgtLl5VU0Kb6K_-0HEFjI4iuDcohyKCk3aVLMDilU-v2O04ZYt7m7bfSv9K043QRF_XPnKBpCPlzdamNBDzmCSIiMLfBrX7JAvy-S22-8FUD9ZjCAl2Lsc337oLVW6ZJ8f7owz7u4P88A1wdxkOhQp7hLDuofq&v=2&itype=2',
            'listing_type' : 'buy',
            'location_accuracy' : '9',
            'longitude' : '-0.13785',
            'price' : 315000,
            'price_coldrent' : 0,
            'price_currency' : 'GBP',
            'price_formatted' : '315,000 GBP',
            'price_high' : 315000,
            'price_low' : 315000,
            'price_type' : 'fixed',
            'property_type' : 'flat',
            'summary' : 'Occupying a residential location between Ditchling Road and Stanford...',
            'thumb_height' : '60',
            'thumb_url' : 'http://2.l.uk.nestoria.nestimg.com/1vb/a/0/1vba0057588a250854fab088470a19e45d556f4474.1.jpg',
            'thumb_width' : '60',
            'title' : 'Rugby Road, Brighton, E. Sussex, BN1',
            'updated_in_days' : 4.5,
            'updated_in_days_formatted' : 'this week'
         },
         {
            'auction_date' : null,
            'bathroom_number' : '2',
            'bedroom_number' : '4',
            'car_spaces' : null,
            'commission' : null,
            'construction_year' : null,
            'datasource_name' : 'FindaProperty.com',
            'guid' : 'g1-jNtMTO4EDN3AwN==',
            'img_height' : '120',
            'img_url' : 'http://2.l.uk.nestoria.nestimg.com/1v0/a/8/1v0a89ef07af46b5e41b6ff8b3f4707ea70b3276c9.2.jpg',
            'img_width' : '160',
            'keywords' : 'Garden, Patio',
            'latitude' : '50.83000',
            'lister_name' : 'King & Chasemore',
            'lister_url' : 'http://rd.nestoria.co.uk/rd?l=WbeVkd5nm5odogZ5y&url=2-ePz73aTBU4LVGFByDI474Ner8aIMqOymkHO7u54s36bamuqdfN_H5rCuKADFLkMNxpsWrUrrDKrao-5HDMOjCyBpoQBCggbXZVLTV0RwIbO22U6qH4zcZxI1J_O7Ailr11v4rwQQzlO_QU4hsnGdHXw5_RrZqpWPvKjJh6N4EnSXliF3AT_AcGByKEhjKBWXGfabCnXeVujJqXvb9JQhii7wmsXVKRQbctPKNb0d7MONwKCYJioE_OCgtLl5VU0Kb6K_-0HEFjI4iuDcohyKCk3aVLMDilU-v2O04ZYt7m7bfSv9K043QRF_XPnKBpCPlzdamNBDzmCSIiMLfBrX7JAvy-S22-8FUD9ZjCAl2Lsc337oLVW6ZJ8f7owz7u4P88A1wdxkOhYj6xvCu4fq&v=2&itype=2',
            'listing_type' : 'buy',
            'location_accuracy' : '9',
            'longitude' : '-0.12896',
            'price' : 290000,
            'price_coldrent' : 0,
            'price_currency' : 'GBP',
            'price_formatted' : '290,000 GBP',
            'price_high' : 290000,
            'price_low' : 290000,
            'price_type' : 'fixed',
            'property_type' : 'house',
            'summary' : 'Guide price: £290,000 £310,000three/four bedroom house situated in the...',
            'thumb_height' : '60',
            'thumb_url' : 'http://1.l.uk.nestoria.nestimg.com/1v0/a/8/1v0a89ef07af46b5e41b6ff8b3f4707ea70b3276c9.1.jpg',
            'thumb_width' : '60',
            'title' : 'Brighton, East Sussex, BN2 - Garden',
            'updated_in_days' : 4.5,
            'updated_in_days_formatted' : 'this week'
         },
         {
            'auction_date' : null,
            'bathroom_number' : '3',
            'bedroom_number' : '4',
            'car_spaces' : null,
            'commission' : null,
            'construction_year' : null,
            'datasource_name' : 'Zoopla',
            'guid' : 'g1-TNtcTM5QTO0UjM=k',
            'img_height' : '120',
            'img_url' : 'http://1.l.uk.nestoria.nestimg.com/1v6/f/0/1v6f00a444f1d467c8b3422816861021dc417d25c7.2.jpg',
            'img_width' : '160',
            'keywords' : 'Garden, En suite',
            'latitude' : '50.83730',
            'lister_name' : 'Austin Gray',
            'lister_url' : 'http://rd.nestoria.co.uk/rd?l=VXeHWPrZYraPaSLrl&url=2-ePz73aTBU4LVGFByDI474Ner8aIMqOymkHO7u54s3aDfmu2aft_C57WuKADFLkMNxpsWrUrrDKrao-5HDMOjCiBhpgBCggbXZVXQV0RwIbO22U6qH4zcZxI1J_O7Ailr3VH4rwQQzlO_QU4hsnGdHXw5_RrZqZGPvK_Dgq52EnSXliN1Aj_PdmByKEhjKBWXGfabCnXeVujfsGHb55U6ny793YvebhMVPsGLJP8DosrHjeqZPidS_a68s7hmA0UMb62xqFaUeHVxiuDT-kmQG06LQadS1Wx26GGq44w-7mLQfTmrLFUqewBkS6PMB4mXlGUHyJYHkDjNIDQCaUaL8YUkmubkh7JZAChTzmR4nuhH3HbgdRTmLJ9XvIw-qP5E&v=2&itype=2',
            'listing_type' : 'buy',
            'location_accuracy' : '9',
            'longitude' : '-0.13812',
            'price' : 830000,
            'price_coldrent' : 0,
            'price_currency' : 'GBP',
            'price_formatted' : '830,000 GBP',
            'price_high' : 830000,
            'price_low' : 830000,
            'price_type' : 'fixed',
            'property_type' : '',
            'summary' : 'Two separate street entrances, entrance halls, 32 through bespoke kitchen...',
            'thumb_height' : '60',
            'thumb_url' : 'http://3.l.uk.nestoria.nestimg.com/1v6/f/0/1v6f00a444f1d467c8b3422816861021dc417d25c7.1.jpg',
            'thumb_width' : '60',
            'title' : 'Springfield Road, Brighton, BN1',
            'updated_in_days' : 30.5,
            'updated_in_days_formatted' : 'a month ago'
         },
         {
            'auction_date' : null,
            'bathroom_number' : '2',
            'bedroom_number' : '2',
            'car_spaces' : null,
            'commission' : null,
            'construction_year' : null,
            'datasource_name' : 'FindaProperty.com',
            'guid' : 'g1-jNtMTO1ADMzMAM==',
            'img_height' : '120',
            'img_url' : 'http://1.l.uk.nestoria.nestimg.com/1v7/d/3/1v7d35a872eae5733f58b5a0778187b9ff40fac8b4.2.jpg',
            'img_width' : '160',
            'keywords' : 'Share of Freehold, Maisonette',
            'latitude' : '50.83640',
            'lister_name' : 'Baron Estates',
            'lister_url' : 'http://rd.nestoria.co.uk/rd?l=VZeJYRtbatcRcUNto&url=2-ePz73aTBU4LVGFByDI494Ner8aIMqOymkHO7u54s36bamuqdfN_H5rCuKADFLkMNxpsWrUrrDKrao-5HDMOjCi5howBCggbXZVTXV0RwIbO22U6qH4zcZxI1J_O7Ailr11TxpgEQzlO_QU4hsnGdHXw5_RrZqpWPvKvLhq9wEnSXlSR2BT_Md2ByKEhjKBWXGfabCnXeVujJqXvb9JQhii7wmsXVKRQbctPKNb0d7MONwKCYJioE_OCgtLl5VU0Kb6K_-0HEFjI4iuDcohyKCk3aVLMDilU-v2O04ZYt7m7bfSv9K043QRF_XPnKBpCPlzdamNBDzmCSIiMLfBrX7JAvy-S22-8FUD9ZjCAl2Lsc337oLVW6ZJ8f7owz7u4P88A1wdxkOhcu7xjGvIfq&v=2&itype=2',
            'listing_type' : 'buy',
            'location_accuracy' : '9',
            'longitude' : '-0.13617',
            'price' : 269950,
            'price_coldrent' : 0,
            'price_currency' : 'GBP',
            'price_formatted' : '269,950 GBP',
            'price_high' : 269950,
            'price_low' : 269950,
            'price_type' : 'fixed',
            'property_type' : '',
            'summary' : 'Offered for sale with no forward chain and a share of freehold is this...',
            'thumb_height' : '60',
            'thumb_url' : 'http://3.l.uk.nestoria.nestimg.com/1v7/d/3/1v7d35a872eae5733f58b5a0778187b9ff40fac8b4.1.jpg',
            'thumb_width' : '60',
            'title' : 'Shaftesbury Pl, Brighton, E. Sussex, BN1',
            'updated_in_days' : 20.5,
            'updated_in_days_formatted' : 'two weeks ago'
         },
         {
            'auction_date' : null,
            'bathroom_number' : '1',
            'bedroom_number' : '4',
            'car_spaces' : null,
            'commission' : null,
            'construction_year' : null,
            'datasource_name' : 'Zoopla',
            'guid' : 'g1-TNtcTMwQTM5ITN=k',
            'img_height' : '120',
            'img_url' : 'http://1.l.uk.nestoria.nestimg.com/1v9/2/6/1v9260ce5497536134f6b83caf92df62f440b29259.2.jpg',
            'img_width' : '160',
            'keywords' : 'Balcony, Garden, Freehold, Maisonette, Terrace, Fireplace',
            'latitude' : '50.83640',
            'lister_name' : 'Fox & Sons',
            'lister_url' : 'http://rd.nestoria.co.uk/rd?l=WaeUjc4ml4ncnfY40&url=2-ePz73aTBU4LVGFByDI474Ner8aIMqOymkHO7u54s36bamuqdfN_H5rCuKADFLkMNxpsWrUrrDKrao-5HDMOjCi1mogBCggbXZVTXV0RwIbO22U6qH4zcZxI1J_O7Ailr1lf4rwQQzlO_QU4hsnGdHXw5_RrZqZGPvKrJgaRxEnySlihyAD_LZ258f099Zg2PU-qbDj_LVrDfsDiP8pUlgyOykIefNQ1Rd8iWe6ERr8ONxuuIKy9X4vKitrxuCEkNZKv7qU-mVGlrjfHVohqbDUnZEqZL515-6Wy2-9xl7WLRamz4LUwYRwxlUbLHHcCbkWEPw5oGmyeZNzcBfgnY-pMj3-Pgj7lVASNMnH12nORaxXu5ex75foZbudVg6aE%3D&v=2&itype=2',
            'listing_type' : 'buy',
            'location_accuracy' : '9',
            'longitude' : '-0.13566',
            'price' : 350000,
            'price_coldrent' : 0,
            'price_currency' : 'GBP',
            'price_formatted' : '350,000 GBP',
            'price_high' : 350000,
            'price_low' : 350000,
            'price_type' : 'fixed',
            'property_type' : 'flat',
            'summary' : 'End of terrace maisonette available with the freehold to the entire...',
            'thumb_height' : '60',
            'thumb_url' : 'http://3.l.uk.nestoria.nestimg.com/1v9/2/6/1v9260ce5497536134f6b83caf92df62f440b29259.1.jpg',
            'thumb_width' : '60',
            'title' : 'Ditchling Rise, Brighton, BN1',
            'updated_in_days' : 496.5,
            'updated_in_days_formatted' : 'over a month ago'
         },
         {
            'auction_date' : null,
            'bathroom_number' : '1',
            'bedroom_number' : '3',
            'car_spaces' : null,
            'commission' : null,
            'construction_year' : null,
            'datasource_name' : 'FindaProperty.com',
            'guid' : 'g1-jNtMTOwMTO3cQM==',
            'img_height' : '120',
            'img_url' : 'http://2.l.uk.nestoria.nestimg.com/1v1/9/8/1v1983bb0b91991bd4098792bd834861e263d99665.2.jpg',
            'img_width' : '160',
            'keywords' : 'Share of Freehold, Maisonette, En suite',
            'latitude' : '50.82870',
            'lister_name' : 'Graves Jenkins',
            'lister_url' : 'http://rd.nestoria.co.uk/rd?l=WWeQfY0ih0jYjbU0x&url=2-ePz73aTBU4LVGFByDI484Ner8aIMqOymkHO7u54s36bamuqdfN_H5rCuKADFLkMNxpsWrUrrDKrao-5HDMOjDSxnowBCggbXZFrUV0RwIbO22U6qH4zcZxI1J_O7Ailr11r8pgEQzlO_QU4hsnGdHXw5_RrZqpWPvKzNgKd0EnSXliJzBj_McGByKEhjKBWXGfabCnXeVujJqXvb9JQhii7wmsXVKRQbctPKNb0d7MONwKCYJioE_OCgtLl5VU0Kb6K_-0HEFjI4iuDcohyKCk3aVLMDilU-v2O04ZYt7m7bfSv9K043QRF_XPnKBpCPlzdamNBDzmCSIiMLfBrX7JAvy-S22-8FUD9ZjCAl2Lsc337oLVW6ZJ8f7owz7u4P88A1wdxkOhQr5hzCvYfq&v=2&itype=2',
            'listing_type' : 'buy',
            'location_accuracy' : '9',
            'longitude' : '-0.14477',
            'price' : 284950,
            'price_coldrent' : 0,
            'price_currency' : 'GBP',
            'price_formatted' : '284,950 GBP',
            'price_high' : 284950,
            'price_low' : 284950,
            'price_type' : 'fixed',
            'property_type' : '',
            'summary' : 'Occupying a central residential location within the west hill conservation...',
            'thumb_height' : '60',
            'thumb_url' : 'http://1.l.uk.nestoria.nestimg.com/1v1/9/8/1v1983bb0b91991bd4098792bd834861e263d99665.1.jpg',
            'thumb_width' : '60',
            'title' : 'Albert Road, Brighton, E. Sussex, BN1',
            'updated_in_days' : 4.5,
            'updated_in_days_formatted' : 'this week'
         },
         {
            'auction_date' : null,
            'bathroom_number' : '1',
            'bedroom_number' : '2',
            'car_spaces' : null,
            'commission' : null,
            'construction_year' : null,
            'datasource_name' : 'Teamprop',
            'guid' : 'g1-DNtgjdtE3TGRGdsJEOvo1QypUUulmV4ZWWVVwd==',
            'img_height' : '120',
            'img_url' : 'http://1.l.uk.nestoria.nestimg.com/1vc/0/6/1vc06e233e7510c84ae2041504e04c1976f2ba826b.2.jpg',
            'img_width' : '160',
            'keywords' : 'Garden, Terrace, Fireplace, Loft, Patio, Central Heating',
            'latitude' : '50.83590',
            'lister_name' : 'Bonetts',
            'lister_url' : 'http://rd.nestoria.co.uk/rd?l=UVe7KDfNMfODOG.fd&url=2-ePz73aTBU4LVGFByDI494Ner8aIMqOymkHO7u54s36bamuqdfN_G5rGpMALFNUMLxpoWrUrrDKrao-5HDMOjCitorABCggbXZVfaV0RwIbO22U6qH4zcZxI1J_O7Ailr11bxpgEQzlO_QU4hsnGdHXw5_RrZqJ6Pua7DgqdsBnKRkShyCjnaaWAreFEzfhXFT-qfRCrLDrDf6WKQ_JclnS3s3YvebhMVPteWOaIVsdLLx_3TDQRwo-6qu6MbXwRZNPj980OKV348gg%3D%3D&v=2&itype=2',
            'listing_type' : 'buy',
            'location_accuracy' : '10',
            'longitude' : '-0.13388',
            'price' : 249950,
            'price_coldrent' : 0,
            'price_currency' : 'GBP',
            'price_formatted' : '249,950 GBP',
            'price_high' : 249950,
            'price_low' : 249950,
            'price_type' : 'fixed',
            'property_type' : 'house',
            'summary' : 'Two bedroom mid terrace period house with through lounge diner and rear...',
            'thumb_height' : '60',
            'thumb_url' : 'http://3.l.uk.nestoria.nestimg.com/1vc/0/6/1vc06e233e7510c84ae2041504e04c1976f2ba826b.1.jpg',
            'thumb_width' : '60',
            'title' : 'Roundhill St, Brighton, E. Sussex, BN2',
            'updated_in_days' : 462.5,
            'updated_in_days_formatted' : 'over a month ago'
         },
         {
            'auction_date' : null,
            'bathroom_number' : '1',
            'bedroom_number' : '2',
            'car_spaces' : null,
            'commission' : null,
            'construction_year' : null,
            'datasource_name' : 'Zoopla',
            'guid' : 'g1-TNtcTM4gDOxQgM==',
            'img_height' : '120',
            'img_url' : 'http://1.l.uk.nestoria.nestimg.com/1v4/7/d/1v47d9ac2a5b2b4d7603962ed3ed4115d260fbabc9.2.jpg',
            'img_width' : '160',
            'keywords' : 'Penthouse, Terrace, Parking, Dishwasher, En suite, Central Heating',
            'latitude' : '50.83710',
            'lister_name' : 'Fox & Sons',
            'lister_url' : 'http://rd.nestoria.co.uk/rd?l=WYeSha2kj2laldW21&url=2-ePz73aTBU4LVGFByDI494Ner8aIMqOimmnO-vZos26DdmuyccN_C57WuKQDEKVsPwYAWrUrrDKrao-5HDMOjDSpkoQBCggbXZVXSV0RwIbO22U6qH4zcZxI1J_O7Ailr0VbxpgEQzlO_QU4hsnGdHXw5_RrZqZGPvKrJgaRxEn2WnSF0BzzBZ258f099Zg2PU-qbDj_LVrDfsDiP8pUlgyOykIefNQ1Rd8iWe6ERr8ONxuuIKy9X4vKiurRnDkEKYuH6sH2KSHNsnPeN8RGNChuKE7951VZ_5HCuq4dm7WPGPz_5NH4kSw1_QLndVMySnWkKwJEV0GSNNyNZYlHF69Fv1u_kj7lKQHcJiX1llO0XnyaiPEq-btZZ_5U%3D&v=2&itype=2',
            'listing_type' : 'buy',
            'location_accuracy' : '9',
            'longitude' : '-0.14245',
            'price' : 449950,
            'price_coldrent' : 0,
            'price_currency' : 'GBP',
            'price_formatted' : '449,950 GBP',
            'price_high' : 449950,
            'price_low' : 449950,
            'price_type' : 'fixed',
            'property_type' : 'flat',
            'summary' : 'Penthouse apartment forming part of the well situated preston mansions...',
            'thumb_height' : '60',
            'thumb_url' : 'http://3.l.uk.nestoria.nestimg.com/1v4/7/d/1v47d9ac2a5b2b4d7603962ed3ed4115d260fbabc9.1.jpg',
            'thumb_width' : '60',
            'title' : 'Preston Park Avenue, Brighton, BN1',
            'updated_in_days' : 688.5,
            'updated_in_days_formatted' : 'over a month ago'
         },
         {
            'auction_date' : null,
            'bathroom_number' : '1',
            'bedroom_number' : '3',
            'car_spaces' : null,
            'commission' : null,
            'construction_year' : null,
            'datasource_name' : 'Zoopla',
            'guid' : 'g1-TNtcTMwUTM3ITN=E',
            'img_height' : '120',
            'img_url' : 'http://1.l.uk.nestoria.nestimg.com/1v6/a/e/1v6ae6709757c4899af0f361ef8f396b6618d0dd09.2.jpg',
            'img_width' : '160',
            'keywords' : 'Garden, Fireplace, Patio',
            'latitude' : '50.83360',
            'lister_name' : 'Austin Gray',
            'lister_url' : 'http://rd.nestoria.co.uk/rd?l=UWe8LEgONgPEPHAgXW&url=2-ePz73aTBU4LVGFByDI484Ner8aIMqOymkHO7u54s36bamuqdfN_G5rKpMATFNUMNxpsWrUrrDKrao-5HDMOjDS5hpABCggbXZVHVV0RwIbO22U6qH4zcZxI1J_O7Ailr1lH4rwQQzlO_QU4hsnGdHXw5_RrZqZGPvK_Dgq52EnSXliJ0ADzIfWByKEhjKBWXGfabCnXeVujfsGHb55U6ny793YvebhMVPsGLJP8DosrHjeqZPidS_a68s7lvC0IPaKWxqFaUeHVxiuDT-kmQG06LQadS1Wx26GGq44w-7mLQfTmrLFUqewBkS6PMB4mXlGQOwJEElzDNIDQCaUaL8YUkmubljrpeAy9bzmR4nuhH3HbgdRTmLJ9XvIw-qP5E&v=2&itype=2',
            'listing_type' : 'buy',
            'location_accuracy' : '9',
            'longitude' : '-0.14610',
            'price' : 330000,
            'price_coldrent' : 0,
            'price_currency' : 'GBP',
            'price_formatted' : '330,000 GBP',
            'price_high' : 330000,
            'price_low' : 330000,
            'price_type' : 'fixed',
            'property_type' : 'house',
            'summary' : 'Brigden Street lies adjacent to Stanford Road and Hamilton Road and is...',
            'thumb_height' : '60',
            'thumb_url' : 'http://3.l.uk.nestoria.nestimg.com/1v6/a/e/1v6ae6709757c4899af0f361ef8f396b6618d0dd09.1.jpg',
            'thumb_width' : '60',
            'title' : 'Brigden Street, Brighton, BN1 - Patio',
            'updated_in_days' : 18.5,
            'updated_in_days_formatted' : 'two weeks ago'
         },
         {
            'auction_date' : null,
            'bathroom_number' : '',
            'bedroom_number' : '4',
            'car_spaces' : null,
            'commission' : null,
            'construction_year' : null,
            'datasource_name' : 'PropertyIndex',
            'guid' : 'g1-TNtMTNzMTN2QAM==',
            'img_height' : '120',
            'img_url' : 'http://3.l.uk.nestoria.nestimg.com/1v9/7/4/1v974ff834fdfb96954a119da312d934dc04d9659a.2.jpg',
            'img_width' : '160',
            'keywords' : '',
            'latitude' : '50.83500',
            'lister_name' : 'Mishon Mackay',
            'lister_url' : 'http://rd.nestoria.co.uk/rd?l=UYe-NGiQPiRGRJCiZZ&url=2-ePz73aTBU4LVGFByDI474Ner8aIMqOimmnO-vZos3KDfnfaYeMDe47SuLwDEKVkPzocFsFyuReef_KNIBs-_CTZhoB1HgATaZkzbVFNsM_3u2Rj8X5TSJ0BrbOCsSXAsx1jqqQYV0gWjKmpd107hHXJ2_VOYvpyAuKjXiKN5C3CKlSF2AD3AcHFnKBEzMUXBGaTNFnGQCf2H6GGC6tQlnS3slprFOQ8QdcKceLEfronBjb_MZXMLpu6gsKMxXwNMMubnvA2rdDMtzKeEqUTROlSLBLpK0V18oFeq5YQuynXcfiL5Nk9qYQJ4Ufr6HI7ZwCkTs-0CjzW6HnMZ&v=2&itype=2',
            'listing_type' : 'buy',
            'location_accuracy' : '9',
            'longitude' : '-0.14102',
            'price' : 625000,
            'price_coldrent' : 0,
            'price_currency' : 'GBP',
            'price_formatted' : '625,000 GBP',
            'price_high' : 625000,
            'price_low' : 625000,
            'price_type' : 'fixed',
            'property_type' : 'house',
            'summary' : 'Three storey, four bedroom period home, which has been sympathetically...',
            'thumb_height' : '60',
            'thumb_url' : 'http://2.l.uk.nestoria.nestimg.com/1v9/7/4/1v974ff834fdfb96954a119da312d934dc04d9659a.1.jpg',
            'thumb_width' : '60',
            'title' : 'Ditchling Rise, Brighton, BN1',
            'updated_in_days' : 12.5,
            'updated_in_days_formatted' : 'last week'
         },
         {
            'auction_date' : null,
            'bathroom_number' : '1',
            'bedroom_number' : '3',
            'car_spaces' : null,
            'commission' : null,
            'construction_year' : null,
            'datasource_name' : 'Zoopla',
            'guid' : 'g1-TNtcTM2QjMyIzN=k',
            'img_height' : '120',
            'img_url' : 'http://2.l.uk.nestoria.nestimg.com/1v3/c/4/1v3c4c3375b782110fa55f9bacbacaec4abcce57aa.2.jpg',
            'img_width' : '160',
            'keywords' : 'Garden, Fireplace, Loft',
            'latitude' : '50.84090',
            'lister_name' : 'Fox & Sons',
            'lister_url' : 'http://rd.nestoria.co.uk/rd?l=VYeIXQsaZsbQbTMsjk&url=2-ePz73aTBU4LVGFByDI484Ner8aIMqOymkHO7u54s36bamuqdfN_H5rCuKADFLkMNxpsWrUrrDKrao-5HDMOjCixorABCggbXYlLaV0RwIbO22U6qH4zcZxI1J_O7Ailr0VDxpgEQzlO_QU4hsnGdHXw5_RrZqZGPvKrJgaRxEnSXliByBTrOdmByKEhjKBWXGfabCnXeVujfsGHb55U6ny793YvebhMVPsGLJP8DosrHjeqZPidS_a68s7hpCEIKaq2xqFaUeHVxiuDT-kmQG06LQadS1Wx26GGq44w-7mLQfTmrLFUqewBkS6PMB4mXlGUIw5EBlTjNIDQCaUaL8YUkmubkiLleBi1TzmR4nuhH3HbgdRTmLJ9XvIw-qP5E&v=2&itype=2',
            'listing_type' : 'buy',
            'location_accuracy' : '9',
            'longitude' : '-0.13488',
            'price' : 429950,
            'price_coldrent' : 0,
            'price_currency' : 'GBP',
            'price_formatted' : '429,950 GBP',
            'price_high' : 429950,
            'price_low' : 429950,
            'price_type' : 'fixed',
            'property_type' : 'house',
            'summary' : 'Period family home which retains many original features. situated just...',
            'thumb_height' : '60',
            'thumb_url' : 'http://1.l.uk.nestoria.nestimg.com/1v3/c/4/1v3c4c3375b782110fa55f9bacbacaec4abcce57aa.1.jpg',
            'thumb_width' : '60',
            'title' : 'St. Andrews Road, Brighton, BN1',
            'updated_in_days' : 42.5,
            'updated_in_days_formatted' : 'over a month ago'
         },
         {
            'auction_date' : null,
            'bathroom_number' : '1',
            'bedroom_number' : '4',
            'car_spaces' : null,
            'commission' : null,
            'construction_year' : null,
            'datasource_name' : 'Zoopla',
            'guid' : 'g1-TNtcTM2ITN3MDM=c',
            'img_height' : '120',
            'img_url' : 'http://2.l.uk.nestoria.nestimg.com/1vc/e/9/1vce9c7bda15078b5de47dbd816855497563b9f929.2.jpg',
            'img_width' : '160',
            'keywords' : 'Garden, Patio, Central Heating',
            'latitude' : '50.83410',
            'lister_name' : 'Fox & Sons',
            'lister_url' : 'http://rd.nestoria.co.uk/rd?l=WaeUjc4ml4ncnfY4vx&url=2-ePz73aTBU4LVGFByDI474Ner8aIMqOymkHO7u54s36bamuqdfN_H5rCuKADFLkMNxpsWrUrrDKrao-5HDMOjDSllrQBCggbXZVbSV0RwIbO22U6qH4zcZxI1J_O7Ailr1lPxpgEQzlO_QU4hsnGdHXw5_RrZqZGPvKrJgaRxEn2RnSF0CzHIZ258f099Zg2PU-qbDj_LVrDfsDiP8pUlgyOykIefNQ1Rd8iWe6ERr8ONxuuIKy9X4vKisLpqCUcIaqv7qU-mVGlrjfHVohqbDUnZEqZL515-6Wy2-9xl7WLRamz4LUwYRwxlUbLHHcCbl2cLwpQDlSeZNzcBfgnY-pMj3-Xmi7hbBC1MnH12nORaxXu5ex75foZbudVg6aE%3D&v=2&itype=2',
            'listing_type' : 'buy',
            'location_accuracy' : '9',
            'longitude' : '-0.14159',
            'price' : 319950,
            'price_coldrent' : 0,
            'price_currency' : 'GBP',
            'price_formatted' : '319,950 GBP',
            'price_high' : 319950,
            'price_low' : 319950,
            'price_type' : 'fixed',
            'property_type' : 'house',
            'summary' : 'Three-storey mid terraced home which is offered for sale & is conveniently...',
            'thumb_height' : '60',
            'thumb_url' : 'http://1.l.uk.nestoria.nestimg.com/1vc/e/9/1vce9c7bda15078b5de47dbd816855497563b9f929.1.jpg',
            'thumb_width' : '60',
            'title' : 'Argyle Road, Brighton, BN1 - Patio',
            'updated_in_days' : 696.5,
            'updated_in_days_formatted' : 'over a month ago'
         },
         {
            'auction_date' : null,
            'bathroom_number' : '1',
            'bedroom_number' : '2',
            'car_spaces' : null,
            'commission' : null,
            'construction_year' : null,
            'datasource_name' : 'FindaProperty.com',
            'guid' : 'g1-jNtMTOxMzN5AAN==',
            'img_height' : '120',
            'img_url' : 'http://2.l.uk.nestoria.nestimg.com/1v7/2/d/1v72d81b0de39d7c80711a415cf3c9174b127a6d60.2.jpg',
            'img_width' : '160',
            'keywords' : 'Garden, Terrace, Victorian, Central Heating',
            'latitude' : '50.83730',
            'lister_name' : 'Whitlock & Heaps',
            'lister_url' : 'http://rd.nestoria.co.uk/rd?l=WUeOdWygfyhWhZSyps&url=2-ePz73aTBU4LVGFByDI494Ner8aIMqOymkHO7u54s36bamuqdfN_G5rGpMATFNEMNxpsWrUrrDKrao-5HDMOjCC5lrABCggbXZVXQV0RwIbO22U6qH4zcZxI1J_O7Ailr11D9rwQQzlO_QU4hsnGdHXw5_RrZqpWPvK_LgK95EnSXliJzBj_IdmByKEhjKBWXGfabCnXeVujJqXvb9JQhii7wmsXVKRQbctPKNb0d7MONwKCYJioE_OCgtLl5VU0Kb6K_-0HEFjI4iuDcohyKCk3aVLMDilU-v2O04ZYt7m7bfSv9K043QRF_XPnKBpCPlzdamNBDzmCSIiMLfBrX7JAvy-S22-8FUD9ZjCAl2Lsc337oLVW6ZJ8f7owz7u4P88A1wdxkOhQq6BvMuIfq&v=2&itype=2',
            'listing_type' : 'buy',
            'location_accuracy' : '9',
            'longitude' : '-0.11658',
            'price' : 225000,
            'price_coldrent' : 0,
            'price_currency' : 'GBP',
            'price_formatted' : '225,000 GBP',
            'price_high' : 225000,
            'price_low' : 225000,
            'price_type' : 'fixed',
            'property_type' : 'house',
            'summary' : 'Victorian terrace house offers good size bright and accommodation...',
            'thumb_height' : '60',
            'thumb_url' : 'http://1.l.uk.nestoria.nestimg.com/1v7/2/d/1v72d81b0de39d7c80711a415cf3c9174b127a6d60.1.jpg',
            'thumb_width' : '60',
            'title' : 'Bear Road, Brighton, E. Sussex, BN2',
            'updated_in_days' : 4.5,
            'updated_in_days_formatted' : 'this week'
         },
         {
            'auction_date' : null,
            'bathroom_number' : '1',
            'bedroom_number' : '2',
            'car_spaces' : null,
            'commission' : null,
            'construction_year' : null,
            'datasource_name' : 'Zoopla',
            'guid' : 'g1-TNtcTN5YDN4cQN==',
            'img_height' : '120',
            'img_url' : 'http://1.l.uk.nestoria.nestimg.com/1v7/3/a/1v73a386cc725a592ffca7452b921882b903b5ca70.2.jpg',
            'img_width' : '160',
            'keywords' : 'Fireplace, Parking, Central Heating',
            'latitude' : '50.83080',
            'lister_name' : 'GK Whites',
            'lister_url' : 'http://rd.nestoria.co.uk/rd?l=UZe.OHjRQjSHSKDjae&url=2-ePz73aTBU4LVGFByDI494Ner8aIMqOymkHO7u54s36bamuqdfN_G5rGpMATFNEMNxpsWrUrrDKrao-5HDMOjCihloABCggbXZVLbV0RwIbO22U6qH4zcZxI1J_O7Ailr11HxpgEQzlO_QU4hsnGdHXw5_RrZqZGPvK7OgKF2EnSXliJ0AzvAdmByKEhjKBWXGfabCnXeVujfsGHb55U6ny793YvebhMVPsGLJP8DosrHjeqZPidS_a68t7pmDkcAaKv7qU-mVGlrjfHVohqbDUnZEqZL515-6Wy2-9xl7WLRamz4LUwYRwxlUbLHHcCfk2gKxpsGhHOONDQWMVrT7JRi2O7kibNZEm4Hi3F4jeBOkSy9blOya48Hvsp-&v=2&itype=2',
            'listing_type' : 'buy',
            'location_accuracy' : '9',
            'longitude' : '-0.13054',
            'price' : 239950,
            'price_coldrent' : 0,
            'price_currency' : 'GBP',
            'price_formatted' : '239,950 GBP',
            'price_high' : 239950,
            'price_low' : 239950,
            'price_type' : 'fixed',
            'property_type' : 'flat',
            'summary' : 'First floor converted flat in a regency period grade 2 listed building...',
            'thumb_height' : '60',
            'thumb_url' : 'http://3.l.uk.nestoria.nestimg.com/1v7/3/a/1v73a386cc725a592ffca7452b921882b903b5ca70.1.jpg',
            'thumb_width' : '60',
            'title' : 'Hanover Crescent, Brighton BN2',
            'updated_in_days' : 18.5,
            'updated_in_days_formatted' : 'two weeks ago'
         },
         {
            'auction_date' : null,
            'bathroom_number' : '1',
            'bedroom_number' : '2',
            'car_spaces' : null,
            'commission' : null,
            'construction_year' : null,
            'datasource_name' : 'FindaProperty.com',
            'guid' : 'g1-jNtMTOxMzNzgwM==',
            'img_height' : '120',
            'img_url' : 'http://3.l.uk.nestoria.nestimg.com/1vf/4/8/1vf485e71e52bb8fc4f25c70fc0c546196929f058d.2.jpg',
            'img_width' : '160',
            'keywords' : '',
            'latitude' : '50.82730',
            'lister_name' : 'Graves Jenkins',
            'lister_url' : 'http://rd.nestoria.co.uk/rd?l=UaeAPIkSRkTITLEkbg&url=2-ePz73aTBU4LVGFByDI494Ner8aIMqOymkHO7u54s36bamuqdfN_G5rGpMALFNUMLxpoWrUrrDKrao-5HDMOjCyFgpQBCggbXZFXQV0RwIbO22U6qH4zcZxI1J_O7Ailr1FX9rwQQzlO_QU4hsnGdHXw5_RrZqpWPvKzNgKd0EnSXliJzBjzBcmByKEhjKBWXGfabCnXeVujJqXvb9JQhii7wmsXVKRQbctPKNb0d7MONwKCYJioE_OCgtLl5VU0Kb6K_-0HEFjI4iuDcohyKCk3aVLMDilU-v2O04ZYt7m7bfSv9K043QRF_XPnKBpCPlzdamNBDzmCSIiMLfBrX7JAvy-S22-8FUD9ZjCAl2Lsc337oLVW6ZJ8f7owz7u4P88A1wdxkOhQq6BPGv4fq&v=2&itype=2',
            'listing_type' : 'buy',
            'location_accuracy' : '9',
            'longitude' : '-0.12901',
            'price' : 175000,
            'price_coldrent' : 0,
            'price_currency' : 'GBP',
            'price_formatted' : '175,000 GBP',
            'price_high' : 175000,
            'price_low' : 175000,
            'price_type' : 'fixed',
            'property_type' : 'house',
            'summary' : 'Terraced property in favoured Hanover area requiring Modernisation and...',
            'thumb_height' : '60',
            'thumb_url' : 'http://2.l.uk.nestoria.nestimg.com/1vf/4/8/1vf485e71e52bb8fc4f25c70fc0c546196929f058d.1.jpg',
            'thumb_width' : '60',
            'title' : 'Scotland St, Brighton, E. Sussex, BN2',
            'updated_in_days' : 4.5,
            'updated_in_days_formatted' : 'this week'
         },
         {
            'auction_date' : null,
            'bathroom_number' : '1',
            'bedroom_number' : '1',
            'car_spaces' : null,
            'commission' : null,
            'construction_year' : null,
            'datasource_name' : 'Zoopla',
            'guid' : 'g1-TNtcTM1ITO2kDO=Q',
            'img_height' : '120',
            'img_url' : 'http://3.l.uk.nestoria.nestimg.com/1vc/7/b/1vc7be703eda93972c406c96913bc891da258fe7ba.2.jpg',
            'img_width' : '160',
            'keywords' : 'Garden, Fireplace, Patio',
            'latitude' : '50.83440',
            'lister_name' : 'Fox & Sons',
            'lister_url' : 'http://rd.nestoria.co.uk/rd?l=VaeKZSucbudSdVOulr&url=2-ePz73aTBU4LVGFByDI4-4Ner8aIMqOymkHO7u54s36bamuqdfN_G5rGpMALFNUMLxpoWrUrrDKrao-5HDMOjCihlpwBCggbXZVbXV0RwIbO22U6qH4zcZxI1J_O7Ailr1FH4rwQQzlO_QU4hsnGdHXw5_RrZqZGPvKrJgaRxEn2RkSN9AjHLZ258f099Zg2PU-qbDj_LVrDfsDiP8pUlgyOykIefNQ1Rd8iWe6ERr8ONxuuIKy9X4vKisLlmA0YAaav7qU-mVGlrjfHVohqbDUnZEqZL515-6Wy2-9xl7WLRamz4LUwYRwxlUbLHHcCbl2QHyJULlieZNzcBfgnY-pMj3-Xlh7JaDC5MnH12nORaxXu5ex75foZbudVg6aE%3D&v=2&itype=2',
            'listing_type' : 'buy',
            'location_accuracy' : '9',
            'longitude' : '-0.13053',
            'price' : 130000,
            'price_coldrent' : 0,
            'price_currency' : 'GBP',
            'price_formatted' : '130,000 GBP',
            'price_high' : 130000,
            'price_low' : 130000,
            'price_type' : 'fixed',
            'property_type' : 'flat',
            'summary' : 'One bedroom ground floor flat which benefits from front and rear patio...',
            'thumb_height' : '60',
            'thumb_url' : 'http://2.l.uk.nestoria.nestimg.com/1vc/7/b/1vc7be703eda93972c406c96913bc891da258fe7ba.1.jpg',
            'thumb_width' : '60',
            'title' : 'Upper Lewes Road, Brighton, BN2',
            'updated_in_days' : 696.5,
            'updated_in_days_formatted' : 'over a month ago'
         },
         {
            'auction_date' : null,
            'bathroom_number' : '1',
            'bedroom_number' : '2',
            'car_spaces' : null,
            'commission' : null,
            'construction_year' : null,
            'datasource_name' : 'Zoopla',
            'guid' : 'g1-TNtcTM0QzNyAzN=U',
            'img_height' : '120',
            'img_url' : 'http://1.l.uk.nestoria.nestimg.com/1v1/6/1/1v16143cab15a669782f74cf076ef644cc2f021c94.2.jpg',
            'img_width' : '160',
            'keywords' : 'Balcony, Lift, Garage',
            'latitude' : '50.83970',
            'lister_name' : 'King & Chasemore',
            'lister_url' : 'http://rd.nestoria.co.uk/rd?l=VZeJYRtbatcRcUNtkr&url=2-ePz73aTBU4LVGFByDI494Ner8aIMqOymkHO7u54s36bamuqdfN_G5rGpMATFNEMNxpsWrUrrDKrao-5HDMOjDStgowBCggbXZVvUV0RwIbO22U6qH4zcZxI1J_O7Ailr11D4rwQQzlO_QU4hsnGdHXw5_RrZqZGPvKjJhKN3EnSXlSZwBj3Pc2ByKEhjKBWXGfabCnXeVujfsGHb55U6ny793YvebhMVPsGLJP8DosrHjeqZPidS_a68s7hrDUAKaqGxqFaUeHVxiuDT-kmQG06LQadS1Wx26GGq44w-7mLQfTmrLFUqewBkS6PMB4mXlGUKxpMBlTTNIDQCaUaL8YUkmubkirxcBi1fzmR4nuhH3HbgdRTmLJ9XvIw-qP5E&v=2&itype=2',
            'listing_type' : 'buy',
            'location_accuracy' : '9',
            'longitude' : '-0.14307',
            'price' : 220000,
            'price_coldrent' : 0,
            'price_currency' : 'GBP',
            'price_formatted' : '220,000 GBP',
            'price_high' : 220000,
            'price_low' : 220000,
            'price_type' : 'fixed',
            'property_type' : 'flat',
            'summary' : 'Ground floor flat two bedrooms living room kitchen bathroom separate w.C...',
            'thumb_height' : '60',
            'thumb_url' : 'http://3.l.uk.nestoria.nestimg.com/1v1/6/1/1v16143cab15a669782f74cf076ef644cc2f021c94.1.jpg',
            'thumb_width' : '60',
            'title' : 'Preston Pk Av, Brighton, E. Sussex, BN1',
            'updated_in_days' : 106.5,
            'updated_in_days_formatted' : 'over a month ago'
         },
         {
            'auction_date' : null,
            'bathroom_number' : '1',
            'bedroom_number' : '2',
            'car_spaces' : null,
            'commission' : null,
            'construction_year' : null,
            'datasource_name' : 'FindaProperty.com',
            'guid' : 'g1-jNtMTO3AzMzkgM==',
            'img_height' : '120',
            'img_url' : 'http://1.l.uk.nestoria.nestimg.com/1v4/f/8/1v4f8f5cf178d65ddb605fd37f920107e2c28293bf.2.jpg',
            'img_width' : '160',
            'keywords' : 'Garden, En suite',
            'latitude' : '50.83690',
            'lister_name' : 'Maslen',
            'lister_url' : 'http://rd.nestoria.co.uk/rd?l=UXe9MFhPOhQFQIBhYg&url=2-ePz73aTBU4LVGFByDI494Ner8aIMqOymkHO7u54s36bamuqdfN_H5rCuKADFLkMNxpsWrUrrDKrao-5HDMOjDStnrQBCggbXZVTaV0RwIbO22U6qH4zcZxI1J_O7Ailr1lX9rwQQzlO_QU4hsnGdHXw5_RrZqpWPvK_NhqByEnSXlSd3ATvAdGByKEhjKBWXGfabCnXeVujJqXvb9JQhii7wmsXVKRQbctPKNb0d7MONwKCYJioE_OCgtLl5VU0Kb6K_-0HEFjI4iuDcohyKCk3aVLMDilU-v2O04ZYt7m7bfSv9K043QRF_XPnKBpCPlzdamNBDzmCSIiMLfBrX7JAvy-S22-8FUD9ZjCAl2Lsc337oLVW6ZJ8f7owz7u4P88A1wdxkOhcs7BLGvofq&v=2&itype=2',
            'listing_type' : 'buy',
            'location_accuracy' : '9',
            'longitude' : '-0.14379',
            'price' : 375000,
            'price_coldrent' : 0,
            'price_currency' : 'GBP',
            'price_formatted' : '375,000 GBP',
            'price_high' : 375000,
            'price_low' : 375000,
            'price_type' : 'fixed',
            'property_type' : 'flat',
            'summary' : 'Two bedroom apartment found on the First floor of this prestigious...',
            'thumb_height' : '60',
            'thumb_url' : 'http://3.l.uk.nestoria.nestimg.com/1v4/f/8/1v4f8f5cf178d65ddb605fd37f920107e2c28293bf.1.jpg',
            'thumb_width' : '60',
            'title' : 'Preston Pk Av, Brighton, E. Sussex, BN1',
            'updated_in_days' : 120.5,
            'updated_in_days_formatted' : 'over a month ago'
         },
         {
            'auction_date' : null,
            'bathroom_number' : '1',
            'bedroom_number' : '1',
            'car_spaces' : null,
            'commission' : null,
            'construction_year' : null,
            'datasource_name' : 'FindaProperty.com',
            'guid' : 'g1-jNtMTOzIzN0AAM==',
            'img_height' : '120',
            'img_url' : 'http://3.l.uk.nestoria.nestimg.com/1vc/c/8/1vcc8aa93bc8df04938605f80d07593b10719c0bf6.2.jpg',
            'img_width' : '160',
            'keywords' : 'High Ceilings',
            'latitude' : '50.83710',
            'lister_name' : 'Kendrick',
            'lister_url' : 'http://rd.nestoria.co.uk/rd?l=UWe8LEgONgPEPHAgYW&url=2-ePz73aTBU4LVGFByDI4-4Ner8aIMqOymkHO7u54s36bamuqdfN_G5rGpMALFNUMLxpoWrUrrDKrao-5HDMOjDSlkowBCggbXZVXSV0RwIbO22U6qH4zcZxI1J_O7Ailr1FT8pgEQzlO_QU4hsnGdHXw5_RrZqpWPvKvLhqF4EnSXliN1Bz3NcmByKEhjKBWXGfabCnXeVujJqXvb9JQhii7wmsXVKRQbctPKNb0d7MONwKCYJioE_OCgtLl5VU0Kb6K_-0HEFjI4iuDcohyKCk3aVLMDilU-v2O04ZYt7m7bfSv9K043QRF_XPnKBpCPlzdamNBDzmCSIiMLfBrX7JAvy-S22-8FUD9ZjCAl2Lsc337oLVW6ZJ8f7owz7u4P88A1wdxkOhUo6BvBvIfq&v=2&itype=2',
            'listing_type' : 'buy',
            'location_accuracy' : '9',
            'longitude' : '-0.14147',
            'price' : 164950,
            'price_coldrent' : 0,
            'price_currency' : 'GBP',
            'price_formatted' : '164,950 GBP',
            'price_high' : 164950,
            'price_low' : 164950,
            'price_type' : 'fixed',
            'property_type' : 'flat',
            'summary' : 'One bedroom raised ground floor flat located next to Preston Park. Property...',
            'thumb_height' : '60',
            'thumb_url' : 'http://2.l.uk.nestoria.nestimg.com/1vc/c/8/1vcc8aa93bc8df04938605f80d07593b10719c0bf6.1.jpg',
            'thumb_width' : '60',
            'title' : 'Stanford Av, Brighton, E. Sussex, BN1',
            'updated_in_days' : 30.5,
            'updated_in_days_formatted' : 'a month ago'
         }
      ],
      'locations' : [
         {
            'center_lat' : '50.837781',
            'center_long' : '-0.137672',
            'long_title' : 'Brighton',
            'place_name' : 'brighton',
            'title' : 'Brighton'
         },
         {
            'center_lat' : '50.797978',
            'center_long' : '0.000600',
            'long_title' : 'Peacehaven, Brighton',
            'place_name' : 'brighton_bn10',
            'title' : 'Brighton'
         }
      ],
      'page' : '1',
      'sort' : 'nestoria_rank',
      'status_code' : '200',
      'status_text' : 'OK',
      'thanks' : 'For using the Nestoria API.',
      'total_pages' : 47,
      'total_results' : 940
   }
}";
  }
}
