//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyFinder
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int actionbar_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int actionbar_tile = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int nostar = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int star = 2130837508;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000c
			public const int do_search = 2131165196;
			
			// aapt resource value: 0x7f070013
			public const int favourites_add_item = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int favourites_remove_item = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int favourites_view_item = 2131165205;
			
			// aapt resource value: 0x7f07000e
			public const int mainview_message = 2131165198;
			
			// aapt resource value: 0x7f070009
			public const int progress = 2131165193;
			
			// aapt resource value: 0x7f070008
			public const int property_details = 2131165192;
			
			// aapt resource value: 0x7f070007
			public const int property_image = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int property_location = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int property_price = 2131165189;
			
			// aapt resource value: 0x7f070003
			public const int property_search_details = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int property_search_price = 2131165188;
			
			// aapt resource value: 0x7f070002
			public const int property_thumb = 2131165186;
			
			// aapt resource value: 0x7f07000a
			public const int propview = 2131165194;
			
			// aapt resource value: 0x7f070012
			public const int recent_search_count = 2131165202;
			
			// aapt resource value: 0x7f070011
			public const int recent_search_text = 2131165201;
			
			// aapt resource value: 0x7f07000f
			public const int recentsearches_header = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int recentsearches_list = 2131165200;
			
			// aapt resource value: 0x7f070001
			public const int result_details = 2131165185;
			
			// aapt resource value: 0x7f07000b
			public const int search = 2131165195;
			
			// aapt resource value: 0x7f070000
			public const int tap_loadmore = 2131165184;
			
			// aapt resource value: 0x7f07000d
			public const int use_location = 2131165197;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int load_more_footer = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int property_search_row = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int property_view = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int PropertyFinderView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int recent_search_row = 2130903044;
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int favourites_toggle = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int favourites_view = 2131099649;
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int do_search_text = 2130968578;
			
			// aapt resource value: 0x7f040007
			public const int favourites_add = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int favourites_remove = 2130968584;
			
			// aapt resource value: 0x7f040006
			public const int favourites_view = 2130968582;
			
			// aapt resource value: 0x7f04000d
			public const int no_result_details = 2130968589;
			
			// aapt resource value: 0x7f04000a
			public const int property_details = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int property_summary = 2130968585;
			
			// aapt resource value: 0x7f040004
			public const int recent_searches = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int recent_searches_count_format = 2130968581;
			
			// aapt resource value: 0x7f04000c
			public const int result_details = 2130968588;
			
			// aapt resource value: 0x7f040001
			public const int search_description = 2130968577;
			
			// aapt resource value: 0x7f04000b
			public const int tap_load_more = 2130968587;
			
			// aapt resource value: 0x7f040003
			public const int use_location_text = 2130968579;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050001
			public const int ActionBar = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int ActionBar_TitleText = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int PropertyFinderTheme = 2131034112;
			
			private Style()
			{
			}
		}
	}
}
