//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyFinder
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int do_search = 2131034113;
			
			// aapt resource value: 0x7f050006
			public const int recent_search_count = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int recent_search_text = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int recentsearches_header = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int recentsearches_list = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int search = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int use_location = 2131034114;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int PropertyFinderView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int recent_search_row = 2130903041;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int do_search_text = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int recent_searches = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int recent_searches_count_format = 2130968581;
			
			// aapt resource value: 0x7f040001
			public const int search_description = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int use_location_text = 2130968579;
			
			private String()
			{
			}
		}
	}
}
